spring:
  application:
    name: investiments
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/investment
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG