spring:
  application:
    name: investiments
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/investment
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
jwt:
  public:
    key: classpath:investmentapp.pub
  private:
    key: classpath:investmentapp
  token:
    expiry: 3600

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
        security: TRACE